name: tanzu-deploy-workflow
on: [push]
jobs:
  tanzu_deploy_job:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Deploy to Tanzu Platform on Commit
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: demo.goharbor.ioghcr.io
          username: zalam 
          password: "Tanzu123@"
      - name: Deploy application to Tanzu Platform
        uses: cpage-pivotal/tanzu-deploy-action@v1.3
        with:
          tanzu_api_token: "1pZI-QhoPsx1Mxp_faGuq7U1gMS2kfYPI1KslPwRRV5WzKuIHPJhfUxQ03jz-ITA" 
          container_registry: demo.goharbor.io/zalam/sensors-workshop
          buildPlanSource: custom-build-plan
          project: workshop01
          space: zahoor-space
